version: "3.4"
services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672 #amqp
      - 15672:15672 #http
      - 15692:15692 #http/prometheus
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 3s
      retries: 30

  gateway:
    build: ./gateway
    depends_on:
      - "rabbitmq"
    env_file:
      - .env
    restart: always

  cache:
    build: ./cache
    restart: always
    volumes:
      - cache/VoiceStateCache.js:node_modules/raincache/dist/cache/VoiceStateCache.js
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
    depends_on:
      - "redis"
      - "rabbitmq"
    env_file:
      - .env

  worker:
    build: ./worker
    restart: always
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
    depends_on:
      - "cache"
    env_file:
      - .env